### ISSUE TITLE
请问能否在文章末尾，增加上一篇，下一篇的功能

### ISSUE THREAD

**Issue by kumakumasan** [tonyyls/gitbook-plugin-theme-fexa#6]
非常喜欢作者这个主题，已经开始使用了，但是，非常希望作者能有空看看，是否能在文章的末尾增加上一篇，下一篇这两个按钮。按钮上如果能显示对应的文章标题就更好了。非常感谢。

**Comment by kumakumasan** [comment]
这是个愚蠢的问题。请忽略。

**Comment by tonyyls** [comment]
可以安装个插件来实现
